/* 
 * REMESITA API REST
 *
 * Api de remesita.com para desarrolladores. Primero obten tu apiKey y apiSecret, y para autenticarte debes ejecutar el endpoint rest/v1/auth en la respuesta obtendrás un token de acceso que debes usar en el resto de peticiones
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing OperationsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class OperationsApiTests
    {
        private OperationsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new OperationsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OperationsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' OperationsApi
            //Assert.IsInstanceOfType(typeof(OperationsApi), instance, "instance is a OperationsApi");
        }

        
        /// <summary>
        /// Test RestV1OperationOrdersGet
        /// </summary>
        [Test]
        public void RestV1OperationOrdersGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? pg = null;
            //int? pgSize = null;
            //DateTime? start = null;
            //DateTime? end = null;
            //string status = null;
            //var response = instance.RestV1OperationOrdersGet(pg, pgSize, start, end, status);
            //Assert.IsInstanceOf<InlineResponse2005> (response, "response is InlineResponse2005");
        }
        
        /// <summary>
        /// Test RestV1OperationP2pGet
        /// </summary>
        [Test]
        public void RestV1OperationP2pGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? pg = null;
            //int? pgSize = null;
            //DateTime? start = null;
            //DateTime? end = null;
            //var response = instance.RestV1OperationP2pGet(pg, pgSize, start, end);
            //Assert.IsInstanceOf<InlineResponse2006> (response, "response is InlineResponse2006");
        }
        
    }

}
