/* 
 * REMESITA API REST
 *
 * Api de remesita.com para desarrolladores. Primero obten tu apiKey y apiSecret, y para autenticarte debes ejecutar el endpoint rest/v1/auth en la respuesta obtendrás un token de acceso que debes usar en el resto de peticiones
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Body1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Body1Tests
    {
        // TODO uncomment below to declare an instance variable for Body1
        //private Body1 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Body1
            //instance = new Body1();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Body1
        /// </summary>
        [Test]
        public void Body1InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Body1
            //Assert.IsInstanceOfType<Body1> (instance, "variable 'instance' is a Body1");
        }


        /// <summary>
        /// Test the property 'BusinessUnitId'
        /// </summary>
        [Test]
        public void BusinessUnitIdTest()
        {
            // TODO unit test for the property 'BusinessUnitId'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'Concept'
        /// </summary>
        [Test]
        public void ConceptTest()
        {
            // TODO unit test for the property 'Concept'
        }
        /// <summary>
        /// Test the property 'IpnUrl'
        /// </summary>
        [Test]
        public void IpnUrlTest()
        {
            // TODO unit test for the property 'IpnUrl'
        }
        /// <summary>
        /// Test the property 'SuccessUrl'
        /// </summary>
        [Test]
        public void SuccessUrlTest()
        {
            // TODO unit test for the property 'SuccessUrl'
        }
        /// <summary>
        /// Test the property 'CancelUrl'
        /// </summary>
        [Test]
        public void CancelUrlTest()
        {
            // TODO unit test for the property 'CancelUrl'
        }
        /// <summary>
        /// Test the property 'CustomId'
        /// </summary>
        [Test]
        public void CustomIdTest()
        {
            // TODO unit test for the property 'CustomId'
        }
        /// <summary>
        /// Test the property 'PayerName'
        /// </summary>
        [Test]
        public void PayerNameTest()
        {
            // TODO unit test for the property 'PayerName'
        }
        /// <summary>
        /// Test the property 'PayerPhone'
        /// </summary>
        [Test]
        public void PayerPhoneTest()
        {
            // TODO unit test for the property 'PayerPhone'
        }
        /// <summary>
        /// Test the property 'PayerEmail'
        /// </summary>
        [Test]
        public void PayerEmailTest()
        {
            // TODO unit test for the property 'PayerEmail'
        }

    }

}
