/* 
 * REMESITA API REST
 *
 * Api de remesita.com para desarrolladores. Primero obten tu apiKey y apiSecret, y para autenticarte debes ejecutar el endpoint rest/v1/auth en la respuesta obtendrás un token de acceso que debes usar en el resto de peticiones
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2009
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse2009Tests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2009
        //private InlineResponse2009 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse2009
            //instance = new InlineResponse2009();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse2009
        /// </summary>
        [Test]
        public void InlineResponse2009InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse2009
            //Assert.IsInstanceOfType<InlineResponse2009> (instance, "variable 'instance' is a InlineResponse2009");
        }


        /// <summary>
        /// Test the property 'PrepaidCardCombinedBalance'
        /// </summary>
        [Test]
        public void PrepaidCardCombinedBalanceTest()
        {
            // TODO unit test for the property 'PrepaidCardCombinedBalance'
        }
        /// <summary>
        /// Test the property 'PrepaidCardCombinedBalanceUsd'
        /// </summary>
        [Test]
        public void PrepaidCardCombinedBalanceUsdTest()
        {
            // TODO unit test for the property 'PrepaidCardCombinedBalanceUsd'
        }
        /// <summary>
        /// Test the property 'ReferralsCommission'
        /// </summary>
        [Test]
        public void ReferralsCommissionTest()
        {
            // TODO unit test for the property 'ReferralsCommission'
        }
        /// <summary>
        /// Test the property 'Usd2mxn'
        /// </summary>
        [Test]
        public void Usd2mxnTest()
        {
            // TODO unit test for the property 'Usd2mxn'
        }

    }

}
