/* 
 * REMESITA API REST
 *
 * Api de remesita.com para desarrolladores. Primero obten tu apiKey y apiSecret, y para autenticarte debes ejecutar el endpoint rest/v1/auth en la respuesta obtendrás un token de acceso que debes usar en el resto de peticiones
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2005Items
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse2005ItemsTests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2005Items
        //private InlineResponse2005Items instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse2005Items
            //instance = new InlineResponse2005Items();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse2005Items
        /// </summary>
        [Test]
        public void InlineResponse2005ItemsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse2005Items
            //Assert.IsInstanceOfType<InlineResponse2005Items> (instance, "variable 'instance' is a InlineResponse2005Items");
        }


        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'SpeedMode'
        /// </summary>
        [Test]
        public void SpeedModeTest()
        {
            // TODO unit test for the property 'SpeedMode'
        }
        /// <summary>
        /// Test the property 'Reference'
        /// </summary>
        [Test]
        public void ReferenceTest()
        {
            // TODO unit test for the property 'Reference'
        }
        /// <summary>
        /// Test the property 'Sku'
        /// </summary>
        [Test]
        public void SkuTest()
        {
            // TODO unit test for the property 'Sku'
        }
        /// <summary>
        /// Test the property 'RecipientAccount'
        /// </summary>
        [Test]
        public void RecipientAccountTest()
        {
            // TODO unit test for the property 'RecipientAccount'
        }
        /// <summary>
        /// Test the property 'Swift'
        /// </summary>
        [Test]
        public void SwiftTest()
        {
            // TODO unit test for the property 'Swift'
        }
        /// <summary>
        /// Test the property 'Institution'
        /// </summary>
        [Test]
        public void InstitutionTest()
        {
            // TODO unit test for the property 'Institution'
        }
        /// <summary>
        /// Test the property 'SenderName'
        /// </summary>
        [Test]
        public void SenderNameTest()
        {
            // TODO unit test for the property 'SenderName'
        }
        /// <summary>
        /// Test the property 'SenderCountry'
        /// </summary>
        [Test]
        public void SenderCountryTest()
        {
            // TODO unit test for the property 'SenderCountry'
        }
        /// <summary>
        /// Test the property 'RecipientName'
        /// </summary>
        [Test]
        public void RecipientNameTest()
        {
            // TODO unit test for the property 'RecipientName'
        }
        /// <summary>
        /// Test the property 'RecipientCountry'
        /// </summary>
        [Test]
        public void RecipientCountryTest()
        {
            // TODO unit test for the property 'RecipientCountry'
        }
        /// <summary>
        /// Test the property 'RecipientRelationship'
        /// </summary>
        [Test]
        public void RecipientRelationshipTest()
        {
            // TODO unit test for the property 'RecipientRelationship'
        }
        /// <summary>
        /// Test the property 'PaymentMethod'
        /// </summary>
        [Test]
        public void PaymentMethodTest()
        {
            // TODO unit test for the property 'PaymentMethod'
        }
        /// <summary>
        /// Test the property 'Quotation'
        /// </summary>
        [Test]
        public void QuotationTest()
        {
            // TODO unit test for the property 'Quotation'
        }
        /// <summary>
        /// Test the property 'SenderCurrency'
        /// </summary>
        [Test]
        public void SenderCurrencyTest()
        {
            // TODO unit test for the property 'SenderCurrency'
        }
        /// <summary>
        /// Test the property 'ExchangeRate'
        /// </summary>
        [Test]
        public void ExchangeRateTest()
        {
            // TODO unit test for the property 'ExchangeRate'
        }
        /// <summary>
        /// Test the property 'LifeTime'
        /// </summary>
        [Test]
        public void LifeTimeTest()
        {
            // TODO unit test for the property 'LifeTime'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'PayedAt'
        /// </summary>
        [Test]
        public void PayedAtTest()
        {
            // TODO unit test for the property 'PayedAt'
        }
        /// <summary>
        /// Test the property 'CancelAt'
        /// </summary>
        [Test]
        public void CancelAtTest()
        {
            // TODO unit test for the property 'CancelAt'
        }
        /// <summary>
        /// Test the property 'CompletedAt'
        /// </summary>
        [Test]
        public void CompletedAtTest()
        {
            // TODO unit test for the property 'CompletedAt'
        }
        /// <summary>
        /// Test the property 'InstitutionIcon'
        /// </summary>
        [Test]
        public void InstitutionIconTest()
        {
            // TODO unit test for the property 'InstitutionIcon'
        }
        /// <summary>
        /// Test the property 'CancelReason'
        /// </summary>
        [Test]
        public void CancelReasonTest()
        {
            // TODO unit test for the property 'CancelReason'
        }
        /// <summary>
        /// Test the property 'Intent'
        /// </summary>
        [Test]
        public void IntentTest()
        {
            // TODO unit test for the property 'Intent'
        }

    }

}
