/* 
 * REMESITA API REST
 *
 * Api de remesita.com para desarrolladores. Primero obten tu apiKey y apiSecret, y para autenticarte debes ejecutar el endpoint rest/v1/auth en la respuesta obtendrás un token de acceso que debes usar en el resto de peticiones
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2008User
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse2008UserTests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2008User
        //private InlineResponse2008User instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse2008User
            //instance = new InlineResponse2008User();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse2008User
        /// </summary>
        [Test]
        public void InlineResponse2008UserInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse2008User
            //Assert.IsInstanceOfType<InlineResponse2008User> (instance, "variable 'instance' is a InlineResponse2008User");
        }


        /// <summary>
        /// Test the property 'Uid'
        /// </summary>
        [Test]
        public void UidTest()
        {
            // TODO unit test for the property 'Uid'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Test]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'PictureUrl'
        /// </summary>
        [Test]
        public void PictureUrlTest()
        {
            // TODO unit test for the property 'PictureUrl'
        }
        /// <summary>
        /// Test the property 'MainCard'
        /// </summary>
        [Test]
        public void MainCardTest()
        {
            // TODO unit test for the property 'MainCard'
        }
        /// <summary>
        /// Test the property 'Level'
        /// </summary>
        [Test]
        public void LevelTest()
        {
            // TODO unit test for the property 'Level'
        }
        /// <summary>
        /// Test the property 'CountryISO'
        /// </summary>
        [Test]
        public void CountryISOTest()
        {
            // TODO unit test for the property 'CountryISO'
        }

    }

}
