/* 
 * REMESITA API REST
 *
 * Api de remesita.com para desarrolladores. Primero obten tu apiKey y apiSecret, y para autenticarte debes ejecutar el endpoint rest/v1/auth en la respuesta obtendrás un token de acceso que debes usar en el resto de peticiones
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2004Items
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse2004ItemsTests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2004Items
        //private InlineResponse2004Items instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse2004Items
            //instance = new InlineResponse2004Items();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse2004Items
        /// </summary>
        [Test]
        public void InlineResponse2004ItemsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse2004Items
            //Assert.IsInstanceOfType<InlineResponse2004Items> (instance, "variable 'instance' is a InlineResponse2004Items");
        }


        /// <summary>
        /// Test the property 'Balance'
        /// </summary>
        [Test]
        public void BalanceTest()
        {
            // TODO unit test for the property 'Balance'
        }
        /// <summary>
        /// Test the property 'BalanceFormatted'
        /// </summary>
        [Test]
        public void BalanceFormattedTest()
        {
            // TODO unit test for the property 'BalanceFormatted'
        }
        /// <summary>
        /// Test the property 'BalanceUSD'
        /// </summary>
        [Test]
        public void BalanceUSDTest()
        {
            // TODO unit test for the property 'BalanceUSD'
        }
        /// <summary>
        /// Test the property 'BalanceUSDFormatted'
        /// </summary>
        [Test]
        public void BalanceUSDFormattedTest()
        {
            // TODO unit test for the property 'BalanceUSDFormatted'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Test]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }
        /// <summary>
        /// Test the property 'NumberFormatted'
        /// </summary>
        [Test]
        public void NumberFormattedTest()
        {
            // TODO unit test for the property 'NumberFormatted'
        }
        /// <summary>
        /// Test the property 'ExchangeRate'
        /// </summary>
        [Test]
        public void ExchangeRateTest()
        {
            // TODO unit test for the property 'ExchangeRate'
        }
        /// <summary>
        /// Test the property 'Clabe'
        /// </summary>
        [Test]
        public void ClabeTest()
        {
            // TODO unit test for the property 'Clabe'
        }
        /// <summary>
        /// Test the property 'CashReference'
        /// </summary>
        [Test]
        public void CashReferenceTest()
        {
            // TODO unit test for the property 'CashReference'
        }
        /// <summary>
        /// Test the property 'Locked'
        /// </summary>
        [Test]
        public void LockedTest()
        {
            // TODO unit test for the property 'Locked'
        }
        /// <summary>
        /// Test the property 'Alias'
        /// </summary>
        [Test]
        public void AliasTest()
        {
            // TODO unit test for the property 'Alias'
        }
        /// <summary>
        /// Test the property 'Main'
        /// </summary>
        [Test]
        public void MainTest()
        {
            // TODO unit test for the property 'Main'
        }

    }

}
