/* 
 * REMESITA API REST
 *
 * Api de remesita.com para desarrolladores. Primero obten tu apiKey y apiSecret, y para autenticarte debes ejecutar el endpoint rest/v1/auth en la respuesta obtendrás un token de acceso que debes usar en el resto de peticiones
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2006Items
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse2006ItemsTests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2006Items
        //private InlineResponse2006Items instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse2006Items
            //instance = new InlineResponse2006Items();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse2006Items
        /// </summary>
        [Test]
        public void InlineResponse2006ItemsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse2006Items
            //Assert.IsInstanceOfType<InlineResponse2006Items> (instance, "variable 'instance' is a InlineResponse2006Items");
        }


        /// <summary>
        /// Test the property 'Match'
        /// </summary>
        [Test]
        public void MatchTest()
        {
            // TODO unit test for the property 'Match'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Test]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'CompletedAt'
        /// </summary>
        [Test]
        public void CompletedAtTest()
        {
            // TODO unit test for the property 'CompletedAt'
        }
        /// <summary>
        /// Test the property 'PaymentMethod'
        /// </summary>
        [Test]
        public void PaymentMethodTest()
        {
            // TODO unit test for the property 'PaymentMethod'
        }
        /// <summary>
        /// Test the property 'Sku'
        /// </summary>
        [Test]
        public void SkuTest()
        {
            // TODO unit test for the property 'Sku'
        }
        /// <summary>
        /// Test the property 'Quotation'
        /// </summary>
        [Test]
        public void QuotationTest()
        {
            // TODO unit test for the property 'Quotation'
        }
        /// <summary>
        /// Test the property 'QuotationCurrency'
        /// </summary>
        [Test]
        public void QuotationCurrencyTest()
        {
            // TODO unit test for the property 'QuotationCurrency'
        }
        /// <summary>
        /// Test the property 'RecipientAccount'
        /// </summary>
        [Test]
        public void RecipientAccountTest()
        {
            // TODO unit test for the property 'RecipientAccount'
        }
        /// <summary>
        /// Test the property 'RecipientAmount'
        /// </summary>
        [Test]
        public void RecipientAmountTest()
        {
            // TODO unit test for the property 'RecipientAmount'
        }

    }

}
